
description = "PaySuper is a unique, simple payment toolkit designed to make developers self-reliant."
## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
release = "1.0"
## Setting this to true will add a "noindex" to *EVERY* page on the site..
removefromexternalsearch = false
flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"