os:
- linux
language: go
go:
- 1.13.x

env:
  global:
  - GO111MODULE=on 

sudo: required

dist: bionic

if: branch in (testhugo)
#cache: bundler

cache:
  directories:
  - $HOME/gopath/pkg/mod

before_install:
#  - sudo snap install hugo --channel=extended
#  - sudo apt-get update
#  - sudo apt-get -y install hugo
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install --tags extended

jobs:
  include: 
    - if: branch = testhugo
      install: true
      script:
      - hugo --environment staging
      - mkdir ./public/api
      - cd $TRAVIS_BUILD_DIR/api-reference 
#      - hugo env
#      - hugo mod vendor 
      - echo $TRAVIS_BUILD_DIR
      - hugo --environment staging && cp -r $TRAVIS_BUILD_DIR/api-reference/public/* ../public/api/
      # deploy:
      #   - provider: pages
      #     skip-cleanup: true
      #     github-token: "$GITHUB_TOKEN"
      #     keep-history: true
      #     target-branch: master
      #     verbose: true
      #     repo: paysuper/paysuper-docs-stage
      #     fqdn: docs.stg.pay.super.com
      #     local-dir: "./public"
      #     on:
      #       branch: develop
    # - if: branch = master
    #   install: true
    #   script:
    #   - hugo --environment production
    #   - echo "docs.pay.super.com" > ./public/CNAME
    #   deploy:
    #     - provider: pages
    #       skip-cleanup: true
    #       github-token: "$GITHUB_TOKEN"
    #       keep-history: true
    #       target-branch: gh-pages
    #       verbose: true
    #       repo: paysuper/paysuper-docs
    #       fqdn: docs.pay.super.com
    #       local-dir: "./public"
    #       on:
    #         branch: master


# notifications:
#   slack:
#     secure: OoFvC851wiCEROz8KhtySp95ijT7fcZvOW8LiLnXxbjU+sWBHhefMdB6hprQFPP3yH6uTOCW2Mn5Vhea3UU8/nJVh0yTXNOapbY3MIa76ss3PgBWCSospyBuX3lJXg8DpxkGs4dVYCxb8FPSdSU4ysjq60zCrWmOykAczD97dXFaq3b7hRSux74aVjwsuaICu0AfNNx1LTgC4/01yXS8Lfg3koMIQRIxfnd/RWNRlKLfDA6nLi9OPgKiwwPkzWZDwWVu8erkjMpZJ9ZICf5ts3p3alIc46Jd22+5vFumdGX3i3DBCo5+Biw/oqBeb7pMNRwg6vpbBMmEUDvOLsHZAaJQAF8zmJYZTSIbaNTs+uD43A5e4NV8Be9G9jWQ+veyKNuCw/li1qLCzyLjUeKuSdjigaoqFTed5GGfp1cZpc/DRo2NMtKi1h/BuZXeqpqOv2PEGOai2GdgDfLlCU3I+2pzKn6hVkEP31a6AA/jP6PlbnhswrEcgizONefA8wyg792bUlqj+k49gfLKl12VnQSi8fvK/z4Br01GTLmDxdx6q1/AQ2nD/aa94haW//0Qck1P1tH3Ph/8aSI1ne9Bxy9dnU4EWBK0ZYZbRWQ1w/QKJJLOtARRn6Cv4FchgL0zzOlCUfgDBmhSNsoSbySMV14HE4mcsehtn7JtlTVNl/A=
