# Config for production

# This is turned off in development as it is relatively slow. 
# This is needed to get accurate lastMod and Git commit info
# on the docs pages.
enableGitInfo = true
baseURL = "https://docs.stg.pay.super.com/"